const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'
const BLOCK_MAXIMUM_GAS = 30000000
const EIP1559_PENALTY_BLOCKS = 5

const PROPOSER_DUTY_URL = '/eth/v1/validator/duties/proposer/'
const SLOT_URL = '/eth/v1/beacon/headers/'
const BEACON_BLOCK_URL = '/eth/v2/beacon/blocks/'
const RELAY_SUBMISSIONS_URL = "/reporter/blocksubmissions"
const RELAY_HEADER_REQUEST_URL = "/reporter/payloaddelivered"
const RELAY_DELIVERED_URL = "/reporter/proposerblindedblocks"
const FINALIZED_BLOCK_URL = '/eth/v2/beacon/blocks/finalized'
const FINALITY_CHECKPOINTS_URL = '/eth/v1/beacon/states/head/finality_checkpoints';
const VALIDATOR_STATE_URL = (blsPubKeyOrIndex) => {
    return `/eth/v1/beacon/states/finalized/validators/${blsPubKeyOrIndex}`
}

const BEACON_SLOT_URL = (BEACON_URL, slot) => {
    return BEACON_URL.concat(BEACON_BLOCK_URL, slot);
}

const SLOTS_IN_EPOCH = 32

const INTERNAL_PENALTY_TYPES = {
    PROPOSER_SLASHED_OR_LOW_EFFECTIVE: 'PROPOSER_SLASHED_OR_LOW_EFFECTIVE',
    BUILDER_UNDERPAYMENT: 'BUILDER_UNDERPAYMENT',
    PROPOSER_OFFLINE: 'PROPOSER_OFFLINE',
    PROPOSER_DID_NOT_SIGN: 'PROPOSER_DID_NOT_SIGN',
    BUILDER_DIDNT_PUBLISH: 'BUILDER_DIDNT_PUBLISH'
}

const INTERNAL_PENALTY_TYPE_TO_CONTRACT_TYPE = {
    PROPOSER_SLASHED_OR_LOW_EFFECTIVE: '2',
    BUILDER_UNDERPAYMENT: '1',
    PROPOSER_OFFLINE: '0',
    PROPOSER_DID_NOT_SIGN: '0',
    BUILDER_DIDNT_PUBLISH: '1'
}

module.exports = {
    ZERO_ADDRESS,
    BLOCK_MAXIMUM_GAS,
    EIP1559_PENALTY_BLOCKS,
    PROPOSER_DUTY_URL,
    SLOT_URL,
    SLOTS_IN_EPOCH,
    BEACON_BLOCK_URL,
    RELAY_SUBMISSIONS_URL,
    RELAY_HEADER_REQUEST_URL,
    RELAY_DELIVERED_URL,
    VALIDATOR_STATE_URL,
    FINALIZED_BLOCK_URL,
    FINALITY_CHECKPOINTS_URL,
    INTERNAL_PENALTY_TYPES,
    INTERNAL_PENALTY_TYPE_TO_CONTRACT_TYPE,
    BEACON_SLOT_URL,
};